urls:
  - https://shopee.vn/Apple-MacBook-Air-(2020)-M1-Chip-13.3-inch-8GB-256GB-SSD-i.88201679.5873954476
  - https://shopee.vn/Đồng-hồ-nam-Fossil-NEUTRA-CHRONO-dây-da-FS5381-màu-đen-i.318790862.10664696259
  - https://shopee.vn/Màn-Hình-Dell-E2016HV-19.5-HD-(1600-x-900)-TN-LED-60Hz-5ms-VGA-Hàng-Ch%C3%ADnh-Hãng-i.273634451.13309490267
  - https://shopee.vn/Đồng-hồ-Kim-nam-Fossil-GRANT-dây-da-FS5061IE-xanh-dương-i.318790862.4393922363
  - https://shopee.vn/Tai-Nghe-Bluetooth-5.0-TWS-Không-Dây-Cảm-Biến-Vân-Tay-Chất-Âm-Êm-Trong-Trẻm-Thời-Lương-Pin-Tốt-i.447624079.11859453588
  - https://shopee.vn/-Mã-ELFLASH3-hoàn-10K-xu-đơn-20K-Miếng-lót-chuột-Bàn-di-chuột-hình-tròn-20-x-20cm-Giá-Rẻ-siêu-dễ-thương-i.160305556.3947807313
  - https://shopee.vn/(BH-12-tháng)-Sạc-Nhanh-PD-18W-USB-C-To-Lightning-Sạc-8-X-11-12-13-(Củ-Sạc-Nhanh-PD-18W-Cáp-Sạc-Nhanh-PD)-i.85794847.3391609027
